### ISSUE TITLE
Out of curiosity - why the original repo was deleted?

### ISSUE THREAD

**Issue by edwinyzh** [Akira13641/dexed#1]
I noticed the dexed project and found it interesting. But just noticed it's been deleted alone with the original author's github account. I'm curious about what happened, anything to say? :)

**Comment by Akira13641** [comment]
I honestly have no idea. I don't really know the original author very well at all (I'd at most spoken to them in passing on the Lazarus forums.)

I just decided to pick up the project because it seemed like a huge waste to let the whole thing slip away.

**Comment by redpiller** [comment]
Original Coder left because of financial problems.

https://forum.dlang.org/post/brfwjkooykageuzafazf@forum.dlang.org
https://forum.dlang.org/post/qhasmt$1qj$1@digitalmars.com
