### ISSUE TITLE
dcd-server doesn't restart if it exits

### ISSUE THREAD

**Issue by DeenOConnor** [Akira13641/dexed#3]
I use dcd for code completion and i have an annoying issue with it. For some reason dcd server fails to process some of my source files, reports a segmentation fault and exits. From that point DexEd can't use the server, but dcd-server process still exists, but now it's a zombie process. I don't know pascal (which i wish i knew), but it seems like the IDE doesn't monitor dcd server state at all. I have to manually restart it every time it fails. It would be great if such monitoring existed and IDE was able to restart dcd server if something happens.

The problem is most likely that i use some libraries that are not in path for dcd to look for, so he tries to load ddoc and completion and then fails.

**Comment by Akira13641** [comment]
I'll take a look at how that part of the IDE works and see if I can come up with something, thanks for letting me know.

**Comment by Akira13641** [comment]
Basile has now started working on Dexed again [here.](https://gitlab.com/basile.b/dexed) I'd recommend opening this issue with him there, if you find this problem persists even with his latest version of the IDE.
