### ISSUE TITLE
build.bat fails on Windows 10

### ISSUE THREAD

**Issue by tastyminerals** [Akira13641/dexed#4]
Attempt to build on Windows 10 throws:
```
dexed\dastworx\src\common.d(6): Error: module lexer is in file 'dparse\lexer.d' which cannot be read
```
Can you provide instructions on how to build the project?

**Comment by DeenOConnor** [comment]
I looked at the paths in build.bat and it seems to me that you just forgot to download dparse and/or put it in ../etc folder.

1 - Download libdparse -> https://github.com/dlang-community/libdparse/
2 - Locate your build.bat
2.1 - If there's no ../etc folder then create it
3 - Create folder libdpase in ../etc and put libdparse sources (src folder) in ../etc/libdparse
4 - Run build.bat again

**Comment by Akira13641** [comment]
You need to check out the submodules for the repo (of which libdparse is one), not just the repo itself. If you [look here](https://github.com/Akira13641/dexed/tree/master/etc), you'll see they're all present.

**Comment by Akira13641** [comment]
Going to close this now as what I mentioned in my last comment is all there really is to it...
