### ISSUE TITLE
Thanks for reviving this

### ISSUE THREAD

**Issue by SadSack963** [Akira13641/dexed#5]
Hi Akira13641

I am new to D, and new to PC programming in general, though I have many years under my belt in an industrial environment using various PLCs. Now that I have retired, I have time to indulge myself in learning new stuff that I've always been interested in but never had the time or energy to persue before (including Linux).

I would like to thank you for picking up this project and maybe improving it over time. It seems to be the only active D IDE around now. 

I had a couple of aborted attempts to install Dlang IDE had to give up in the end, and I couldn't even find the NetBeans plug-in. After a bit of a fight, I did manage to get the Eclipse DDT Plug-In working, and though it's not 100% and seems to be no longer in development, it is useable - at least for me with my current learning path. Once I get a bit more familiar with it I shall have a go at installing dexed.

As someone new to programming for PC, and by no means an expert in Linux, I think that the lack of a good IDE for D is probably one of the biggest things preventing take-up of the language. I have no desire to fight against a command-line compiler when all I want to do is learn the language. An IDE makes things clearer than a list of error messages, and so much easier and quicker to edit (at least, it does for us beginners).

Thank you once again, and good luck with the project.

Regards,
SadSack963

**Comment by Akira13641** [comment]
Thanks, and no problem! I'm hoping to get back into doing some more work on this soon, probably starting with looking at the `dcd-server` issue someone opened another issue about.
