### ISSUE TITLE
Newbie trying to compile for Win64

### ISSUE THREAD

**Issue by devregnfo** [Akira13641/dexed#6]
Hi,
I was over the original page and following the install instructions and got stuck.
I found your repo and cloned it... and can't figure out how to compile it for Windows.

Is there a full description on how to build it?
This old one is what I found:
https://basile.b.gitlab.io/dexed/build.html

Thanks so much!

**Comment by Akira13641** [comment]
When you cloned it, did you also check out the submodules? (Meaning, you have all the folders [shown here](https://github.com/Akira13641/dexed/tree/master/etc) in your copy of the "etc" folder).

If so, what was the issue you were running into exactly? Are you getting a compiler error while building the Lazarus project file?

**Comment by Akira13641** [comment]
Basile has now started working on Dexed again [here](https://gitlab.com/basile.b/dexed), and provides prebuilt Windows 64 binaries directly.
